# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20170531_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaFile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
