# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20170602_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaFile',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
