# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20170611_0707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
