# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20170713_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
    ]
